### ISSUE TITLE
Sentinel Support....Support it inject into an existing layout.

### ISSUE THREAD

**Issue by bcodermicro** [Team-Tea-Time/laravel-forum-demo#2]
I was wondering if your forum supprts Sentinel authorization as well as the ability to inject the forum in to a site which has an existing layout. So basically a non styled forum. 

Thanks

**Comment by Riari** [comment]
The package uses Laravel's auth interface, so assuming Sentinel uses that, the forum should have no issue picking up sessions and users.

As for the style, it's designed to work well with Bootstrap CSS out of the box, but you can change the markup however you see fit. If you need to integrate the forum with an existing design that doesn't use Bootstrap, just publish the views (this is done slightly differently depending on the package version) and tweak them accordingly.

**Comment by bcodermicro** [comment]
thanks...Sentinel is a cartalyst package for authentication which is more involved then the Laravel Auth package. I'd need to explore your package a bit to see if I can get it to run with Sentinel as well. 

thanks

**Comment by maximusblade** [comment]
@bostonmacosx did you find much success in this?
