### ISSUE TITLE
Instruction for upgrading to laravel 4.1 forum & its frontend

### ISSUE THREAD

**Issue by silverbrick** [Team-Tea-Time/laravel-forum-demo#4]
Hey you are doing a great work..keep it up..i am having issue with old version of forum because my website use bootstrap 4 & your old forum was build on 3..kindly give installing instruction for latest forum & its frontend

**Comment by Riari** [comment]
Hi,

You can just follow the installation instructions given in the docs.

laravel-forum: https://teamteatime.net/docs/laravel-forum/4.x/installation.md
laravel-forum-frontend: https://teamteatime.net/docs/laravel-forum/4.x/front-end.installation.md

After going through that, you can modify the views in `resources/views/vendor/forum` to replace Bootstrap with version 4 and do whatever else you need.

I am planning to upgrade the frontend package to use Bootstrap 4, but I have no specific deadline for that so this is your only option for now.

**Comment by silverbrick** [comment]
okay thanks ^^ but i would be really thankful if you can give me the instruction for installing this demo package which is already boostrap 4 i think !!

**Comment by Riari** [comment]
It's not. This demo is running the packages with default views, config, etc.
