### ISSUE TITLE
Where can I find "seeding" content for demo version?

### ISSUE THREAD

**Issue by NDanilov2015** [Team-Tea-Time/laravel-forum-demo#5]
Hi! Where I can find seeding files for database used in this demo-version?
https://github.com/Team-Tea-Time/laravel-forum-demo
https://laravel-forum.teamteatime.net/

I install demo version of forum, and can't know how correctly fill database tables to get similar structure.

Also I want do auth with password using, what need change for it?

Also I want enable register of new users)

**Comment by Riari** [comment]
(Answered in https://github.com/Team-Tea-Time/laravel-forum/issues/244)
