### ISSUE TITLE
Deleting post dont work.

### ISSUE THREAD

**Issue by midway99** [Team-Tea-Time/laravel-forum-demo#6]
HI!I installed demo version laravel-forum ,and deleting dont work corectly after installed,in the https://laravel-forum.teamteatime.net/ too,this feature working in you core repository laravel-forum?
![2021-09-10_15-53](https://user-images.githubusercontent.com/18192716/132856428-d4739d43-dbcf-4e74-ac45-d4d5e7846e6e.png)

**Comment by Riari** [comment]
Hi,

It looks like the "Select all posts" checkbox is mistakenly showing up even if the user you're logged in as does not have permission to delete posts. This is almost certainly an issue in the views from the package itself; I'll try to work on a fix ASAP.

If you want to use the package and allow deleting posts, just make sure you're overriding the `ThreadPolicy::deletePosts` and `PostPolicy::delete` methods to grant them to the appropriate user(s).

Thanks

**Comment by Riari** [comment]
Fixed in https://github.com/Team-Tea-Time/laravel-forum/pull/271 and released in [5.0.9](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.0.9).
